/* Ayudante Albion — historial y eficiencia de mazmorras. */
(function(root){'use strict';
var KEY='dungeonRuns',SETTINGS='dungeonSettings';
var TYPES={all:'Resumen',solo:'Mazmorra en solitario',standard:'Mazmorra estándar',static:'Mazmorras estáticas',avalonian:'Mazmorra avaloniana',corrupted:'Corrupta',hellgate:'Hellgate',hce:'HCE (Expedición)',mists:'Nieblas',knightfall:'Abadía de Knightfall',abyssal:'Abyssal Depths',ancient:'Ancient Lands'};
var MAIN=['all','solo','standard','static','avalonian','corrupted','hellgate','hce','mists'],SUB=['knightfall','abyssal','ancient'];
var RANGES=[[30,'30 Minutos'],[60,'1 Hora'],[180,'3 Horas'],[720,'12 Horas'],[1440,'24 Horas'],[4320,'3 Días'],[10080,'7 Días'],[43200,'30 Días'],[525600,'365 Días']];
var S={rows:[],range:30,type:'all',tier:0,enchant:-1,includeParty:false,selected:new Set()};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function n(v,d){return new Intl.NumberFormat('es-AR',{maximumFractionDigits:d||0,minimumFractionDigits:d||0}).format(Number(v)||0)}function silver(v){return n(v)+' plata'}function dur(s){s=Math.max(0,+s||0);return Math.floor(s/60)+'m '+(Math.floor(s)%60)+'s'}function id(){return'dng_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function read(k,f){try{var x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch(e){return f}}function save(){try{localStorage.setItem(KEY,JSON.stringify(S.rows.slice(-5000)));localStorage.setItem(SETTINGS,JSON.stringify({includeParty:S.includeParty}))}catch(e){}}
function norm(x){if(!x||typeof x!=='object')return null;var type=String(x.type||x.dungeonType||'standard').toLowerCase();if(!TYPES[type])type='standard';return{uid:String(x.uid||id()),ts:+(x.ts||x.endedAt||Date.now()),type:type,tier:Math.max(1,Math.min(8,+(x.tier||1))),enchant:Math.max(0,Math.min(4,+(x.enchantment||x.enchant||0))),map:String(x.map||x.zone||TYPES[type]),duration:Math.max(0,+(x.duration||x.seconds||0)),fame:Math.max(0,+(x.fame||0)),respec:Math.max(0,+(x.respec||0)),might:Math.max(0,+(x.might||x.power||0)),favor:Math.max(0,+(x.favor||0)),silver:Math.max(0,+(x.silver||0)),loot:Math.max(0,+(x.lootValue||x.loot||0)),partyLoot:Math.max(0,+(x.partyLootValue||x.partyLoot||0)),deaths:Math.max(0,+(x.deaths||0)),chests:Math.max(0,+(x.chests||0))}}
function add(x){var r=norm(x);if(!r||S.rows.some(function(a){return a.uid===r.uid}))return false;S.rows.push(r);save();render();return true}
function inRange(r,offset){var end=Date.now()-S.range*60000*(offset||0),start=end-S.range*60000;return r.ts>=start&&r.ts<=(offset?end:Date.now())}
function filtered(offset){return S.rows.filter(function(r){return inRange(r,offset)&&(S.type==='all'||r.type===S.type)&&(!S.tier||r.tier===S.tier)&&(S.enchant<0||r.enchant===S.enchant)})}
function sums(rows){return rows.reduce(function(a,r){a.runs++;['fame','respec','might','favor','silver','deaths','chests'].forEach(function(k){a[k]+=r[k]});a.loot+=r.loot+(S.includeParty?r.partyLoot:0);a.duration+=r.duration;return a},{runs:0,fame:0,respec:0,might:0,favor:0,silver:0,loot:0,deaths:0,chests:0,duration:0})}
function trend(cur,prev,key){var c=key==='avg'?cur.duration/(cur.runs||1):cur[key],p=key==='avg'?prev.duration/(prev.runs||1):prev[key],pct=p?(c-p)/p*100:(c?100:0);return(pct>=0?'↑ ':'↓ ')+n(Math.abs(c-p))+' ('+n(Math.abs(pct),2)+'%)'}
function group(rows,key){var o={};rows.forEach(function(r){var k=r[key],g=o[k]||(o[k]={key:k,runs:0,loot:0,fame:0,duration:0,chests:0});g.runs++;g.loot+=r.loot+(S.includeParty?r.partyLoot:0);g.fame+=r.fame;g.duration+=r.duration;g.chests+=r.chests});return Object.values(o)}function top(a,key){return a.length?a.slice().sort(function(x,y){return y[key]-x[key]})[0]:null}
function shell(){var m=document.getElementById('dungeonsMount');if(!m)return;m.innerHTML='<div class="dng-shell"><div class="panel dng-toolbar"><div class="dng-title"><small>ANALYTICS · DUNGEONS</small><h1>Seguimiento de mazmorras</h1></div><span class="dng-state" id="dngState" title="El rastreo se activa en la pestaña Sesión. Esta pestaña registra sola mientras haya personaje detectado."><input id="dngTracking" type="checkbox" disabled tabindex="-1" aria-hidden="true"><i></i><span id="dngStateText">Activá el tracking en la pestaña Sesión</span></span><label class="dng-select"><span>Rango de tiempo</span><select id="dngRange">'+RANGES.map(function(x){return'<option value="'+x[0]+'" '+(x[0]===S.range?'selected':'')+'>'+x[1]+'</option>'}).join('')+'</select></label></div><div class="dng-tabs" id="dngTabs">'+tabs(MAIN)+'</div><div class="dng-subtabs" id="dngSubtabs">'+tabs(SUB)+'</div><div class="panel dng-filters"><div><span class="dng-filter-label">Nivel (Tier)</span><div class="dng-chips" id="dngTiers">'+chips([0,1,2,3,4,5,6,7,8],S.tier,function(x){return x?'T'+x:'Todos'})+'</div></div><div><span class="dng-filter-label">Encantamiento</span><div class="dng-chips" id="dngEnchants">'+chips([-1,0,1,2,3,4],S.enchant,function(x){return x<0?'Todos':x})+'</div></div></div><div class="dng-kpis" id="dngKpis"></div><div class="dng-overview"><div class="panel gat-card"><h2>Resumen de mazmorra</h2><div class="dng-summary-grid" id="dngSummary"></div></div><div class="panel gat-card"><h2>Eficiencia de las partidas</h2><div class="dng-eff" id="dngEfficiency"></div></div></div><div class="dng-management"><div class="panel gat-card"><h2>Configuración y gestión de datos</h2><label class="dng-check"><input id="dngPartyLoot" type="checkbox"> Incluir botín de jugadores</label><div class="dng-danger-grid"><button class="dng-danger" data-action="selected">Eliminar mazmorras seleccionadas</button><button class="dng-danger" data-action="zero">Eliminar mazmorras con 0 de fama</button><button class="dng-danger" data-action="all">Reiniciar seguimiento de mazmorra</button><button class="dng-danger" data-action="today">Reiniciar mazmorras de hoy</button></div></div><div class="panel gat-card"><h2>Partidas recientes</h2><div class="table-wrap"><table class="ledger"><thead><tr><th><input id="dngSelectAll" type="checkbox" aria-label="Seleccionar visibles"></th><th>Tipo / mapa</th><th>Nivel</th><th class="num">Fama</th><th class="num">Botín</th><th>Duración</th></tr></thead><tbody id="dngRows"></tbody></table></div></div></div></div>';wire();paintTracking();render()}
function tabs(a){return a.map(function(k){return'<button data-dng-type="'+k+'" class="'+(S.type===k?'active':'')+'">'+TYPES[k]+'</button>'}).join('')}function chips(a,on,label){return a.map(function(x){return'<button class="dng-chip '+(x===on?'active':'')+'" data-value="'+x+'">'+label(x)+'</button>'}).join('')}
function wire(){document.getElementById('dngRange').onchange=function(e){S.range=+e.target.value;render()};document.querySelectorAll('[data-dng-type]').forEach(function(b){b.onclick=function(){S.type=b.dataset.dngType;document.querySelectorAll('[data-dng-type]').forEach(function(x){x.classList.toggle('active',x===b)});render()}});document.getElementById('dngTiers').onclick=function(e){var b=e.target.closest('[data-value]');if(!b)return;S.tier=+b.dataset.value;activeChip(b);render()};document.getElementById('dngEnchants').onclick=function(e){var b=e.target.closest('[data-value]');if(!b)return;S.enchant=+b.dataset.value;activeChip(b);render()};document.getElementById('dngPartyLoot').checked=S.includeParty;document.getElementById('dngPartyLoot').onchange=function(e){S.includeParty=e.target.checked;save();render()};document.querySelector('.dng-danger-grid').onclick=function(e){var b=e.target.closest('[data-action]');if(b)remove(b.dataset.action)};document.getElementById('dngRows').onchange=function(e){var c=e.target.closest('[data-uid]');if(!c)return;c.checked?S.selected.add(c.dataset.uid):S.selected.delete(c.dataset.uid);renderRows(filtered())};document.getElementById('dngSelectAll').onchange=function(e){filtered().forEach(function(r){e.target.checked?S.selected.add(r.uid):S.selected.delete(r.uid)});renderRows(filtered())}}
function activeChip(b){b.parentElement.querySelectorAll('.dng-chip').forEach(function(x){x.classList.toggle('active',x===b)})}// El registro sigue al tracking de Sesión: no se activa desde acá. Mientras
// haya captura y personaje detectado, las partidas se acumulan aunque el
// usuario nunca abra esta pestaña.
function trackingState(){if(!root.AATracker)return{capturing:false,available:false,detected:false};var st=AATracker.state(),demo=!!(st.capture&&st.capture.phase==='demo');return{capturing:!!st.capturing,available:!!st.available,detected:demo||(!!st.identityValid&&st.filterMatched!==false)}}
function trackingLabel(st){if(!st.available)return'El motor de captura no está disponible';if(!st.capturing)return'Activá el tracking en la pestaña Sesión';if(!st.detected)return'Capturando · esperando detectar tu personaje';return'Registrando automáticamente'}
function paintTracking(){var box=document.getElementById('dngState');if(!box)return;var st=trackingState(),on=st.capturing&&st.detected,t=document.getElementById('dngTracking');t.checked=on;t.disabled=true;box.classList.toggle('on',on);document.getElementById('dngStateText').textContent=trackingLabel(st)}
function kpi(icon,label,val,sub,color){return'<div class="dng-kpi"><div class="dng-kpi-head"><span class="dng-kpi-icon" style="--dng-color:'+color+'">'+icon+'</span>'+label+'</div><strong>'+esc(val)+'</strong><small>'+esc(sub)+'</small></div>'}function summary(label,val,sub){return'<div class="dng-summary-card"><span>'+label+'</span><strong>'+esc(val)+'</strong><small>'+esc(sub)+'</small></div>'}
function render(){if(!document.getElementById('dngKpis'))return;var rows=filtered(),cur=sums(rows),prev=sums(filtered(1)),hours=Math.max(cur.duration/3600,1/60),avg=cur.duration/(cur.runs||1);document.getElementById('dngKpis').innerHTML=kpi('➤','Total de partidas',n(cur.runs),trend(cur,prev,'runs'),'#a978ff')+kpi('▣','Fama total',n(cur.fame)+' ('+n(cur.fame/hours)+' /h)',trend(cur,prev,'fame'),'#ec6370')+kpi('◆','ReSpec total',n(cur.respec)+' ('+n(cur.respec/hours)+' /h)',trend(cur,prev,'respec'),'#d9a441')+kpi('✦','Poder total',n(cur.might)+' ('+n(cur.might/hours)+' /h)',trend(cur,prev,'might'),'#5b9cff')+kpi('❖','Favor total',n(cur.favor)+' ('+n(cur.favor/hours)+' /h)',trend(cur,prev,'favor'),'#65c7b0')+kpi('●','Plata total',n(cur.silver)+' ('+n(cur.silver/hours)+' /h)',trend(cur,prev,'silver'),'#dfbb55')+kpi('▰','Valor total loteado',n(cur.loot)+' ('+n(cur.loot/hours)+' /h)',trend(cur,prev,'loot'),'#d58a4e')+kpi('☠','Muertes en mazmorras',n(cur.deaths),trend(cur,prev,'deaths'),'#ef656b')+kpi('◷','Duración promedio',dur(avg),trend(cur,prev,'avg'),'#55a7db');var tiers=group(rows,'tier').map(function(g){g.profit=g.loot/(g.runs||1);return g}),maps=group(rows,'map'),prof=top(tiers,'profit'),played=top(tiers,'runs'),loot=top(rows,'loot'),map=top(maps,'loot'),fast=rows.length?rows.slice().sort(function(a,b){return a.duration-b.duration})[0]:null;document.getElementById('dngSummary').innerHTML=summary('Nivel más rentable',prof?'T'+prof.key:'—',prof?'Botín promedio: '+silver(prof.profit):'Valor del botín: —')+summary('Nivel más jugado',played?'T'+played.key:'—',n(played?played.runs:0)+' ejecuciones')+summary('Botín más valioso',silver(loot?loot.loot:0),loot?loot.map:'—')+summary('Mejor mapa de mazmorra',map?map.key:'—',map?'Promedio de botín: '+silver(map.loot/map.runs):'Promedio de botín: —')+summary('Partida más rápida',fast?dur(fast.duration):'—',fast?TYPES[fast.type]:'Sin partidas')+summary('Promedio de cofres / partida',n(cur.chests/(cur.runs||1),2),n(cur.chests)+' cofres');document.getElementById('dngEfficiency').innerHTML=eff('Promedio de botín / partida',silver(cur.loot/(cur.runs||1)))+eff('Promedio de fama / partida',n(cur.fame/(cur.runs||1)))+eff('Duración promedio',dur(avg))+eff('Fama por hora',n(cur.fame/hours))+eff('Plata + botín por hora',silver((cur.silver+cur.loot)/hours));renderRows(rows)}function eff(a,b){return'<div class="dng-eff-row"><span>'+a+'</span><strong>'+esc(b)+'</strong></div>'}
function renderRows(rows){var body=document.getElementById('dngRows'),recent=rows.slice().sort(function(a,b){return b.ts-a.ts}).slice(0,100);body.innerHTML=recent.length?recent.map(function(r){return'<tr class="'+(S.selected.has(r.uid)?'dng-selected':'')+'"><td><input type="checkbox" data-uid="'+esc(r.uid)+'" '+(S.selected.has(r.uid)?'checked':'')+'></td><td><span class="dng-run-type">'+TYPES[r.type]+'</span><br><small class="muted">'+esc(r.map)+' · '+new Date(r.ts).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+'</small></td><td>T'+r.tier+'.'+r.enchant+'</td><td class="num">'+n(r.fame)+'</td><td class="num">'+silver(r.loot+(S.includeParty?r.partyLoot:0))+'</td><td>'+dur(r.duration)+'</td></tr>'}).join(''):'<tr><td colspan="6" class="dng-empty">Todavía no se registraron partidas para estos filtros.</td></tr>';var all=document.getElementById('dngSelectAll');all.checked=!!recent.length&&recent.every(function(r){return S.selected.has(r.uid)});all.indeterminate=recent.some(function(r){return S.selected.has(r.uid)})&&!all.checked}
function remove(action){var today=new Date();today.setHours(0,0,0,0);var count=action==='selected'?S.selected.size:action==='zero'?S.rows.filter(function(r){return!r.fame}).length:action==='today'?S.rows.filter(function(r){return r.ts>=+today}).length:S.rows.length;if(!count)return;if(!confirm('¿Eliminar '+count+' registro'+(count===1?'':'s')+' de mazmorra? Esta acción no se puede deshacer.'))return;if(action==='selected')S.rows=S.rows.filter(function(r){return!S.selected.has(r.uid)});else if(action==='zero')S.rows=S.rows.filter(function(r){return r.fame!==0});else if(action==='today')S.rows=S.rows.filter(function(r){return r.ts<+today});else S.rows=[];S.selected.clear();save();render()}
function init(){var set=read(SETTINGS,{});S.includeParty=!!set.includeParty;S.rows=read(KEY,[]).map(norm).filter(Boolean);shell();if(root.AATrackerAnalytics){AATrackerAnalytics.subscribe(function(payload,type){paintTracking();if(type==='dungeon'||type==='dungeonRun')add(payload)});AATrackerAnalytics.detect().then(paintTracking).catch(paintTracking)}setInterval(function(){if(S.rows.length&&document.getElementById('dngKpis'))render()},1000)}root.AADungeons=Object.freeze({add:add,render:render,rows:function(){return S.rows.slice()}});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init()}(window));
